### ISSUE TITLE
Constructor not found when running  Check Code  -  Vcs 2010  / .net 4.0.3  supported ?

### ISSUE THREAD

**Issue by mstramb** [davispuh/gear-emu#13]
The following minimal plugin code throws a 'Constructor on type 'Test1' not found.' when I run the Check Code (button), from the current repo.

It throws the same error from larger scripts, I trimmed it down to the minimum to try to discover the problem.

The same script and the others in ver 14.7.3.0  run fine.

I'm building the source with Vcs 2010  /  .net v4.0.30319 ,  is that the problem ?

(I edited the sln file, changing Format Version 12.00  to Format Version 11_

    <plugin>
      <instance class="Test1" />
      <code>
    using Gear.PluginSupport; 
     class Test1:PluginBase
     {
       public Test1() {
          int foo;
       }
   }
   </code>
   </plugin>

**Comment by gatuno1** [comment]
Hello mstramb:
   The specific problem with this plugin code is the invocation of default constructor with no parameters. This development version need the constructor have a `PropellerCPU chip` parameter type, also with the invocation of base class constructor:
```C#
    <code>
    using Gear.PluginSupport; 
     class Test1:PluginBase 
     {
         public Test1(PropellerCPU chip) : base(chip)
              int foo;
         }
     }
     ... 
```
This happens because we are in middle of development for an updated plugin system, is not a bug but a change in implementation.  This implies changes in the plugin base class, as the needing of invoke the base constructor with the shown parameter, the inclusion of a PropellerCPU reference in all the plugins by default, new method for close event and to drive pins more explicit.

The known plugins availables in Propeller Forum are updated in the `gear-emu/plug-ins/` folder, so you can see the necesary changes to work with this. Also you can see the plugin base class definition on  `gear-emu/Gear/PluginSupport/PluginBase.cs` with the modifications documented.

**Comment by mstramb** [comment]
Thanks !    Just to clean up a bit :

    public Test1(PropellerCPU chip) : base(chip) 
    {
              int foo;
      }

And to complete it :  (at least currently )  this is now working :

<plugin>
  <instance class="Test1" />
  <code>
using Gear.PluginSupport; 
using Gear.EmulationCore;
 
class Test1:PluginBase
 {
   
 public Test1(PropellerCPU chip) : base (chip) {
      int foo;
   }
}
</code>
</plugin>
