### ISSUE TITLE
Linux-Mono: Version 22.06.02 crashes directly after loading a binary.

### ISSUE THREAD

**Issue by gatuno1** [davispuh/gear-emu#30]
A déjà vu:  Version 22.6.2.0 crashes directly after loading a binary.

Debian11's mono-complete is installed.

Maybe [gear220602.log.txt.gz](https://github.com/davispuh/gear-emu/files/8984095/gear220602.log.txt.gz) helps a bit?

v220601 crashes too, but not v220504.

_Originally posted by @drawkula in https://github.com/davispuh/gear-emu/issues/14#issuecomment-1166214467_

**Comment by gatuno1** [comment]
Well, it was two bugs on code, not related with loading a plugin #14 : so I created this new issue.
The log from @drawkula helps a lot, and its guide me to found a second bug of the same style.
I'm generating a new release with the hot fix.

**Comment by gatuno1** [comment]
OK, I generated a new version v22.06.03 with a fix for this bug.

**Comment by drawkula** [comment]
Thanks!

+ I can confirm it loads boinaries without crashing.
+ Help->About still shows "Version: 22.6.2.0
+ I still cannot change Logic-Probe's "Time Frame" and "Tick Mark Grid" parameters.
  I git used to it and meanwhile don't even miss it much any more... ;-)
  #15

**Comment by gatuno1** [comment]
Thanks for the report! I'm glad that it is running normally. Could you try loading a plugin?

- The about is easy to repair. I'll do in a new commit, reposting the release also.
- The logic probe problem #15 is not easy: something about reflexion in mono...

**Comment by drawkula** [comment]
It still shows some messages after loading the binary.  That may or may not be interesting but here is a log:   [log220603.log.txt.gz](https://github.com/davispuh/gear-emu/files/8988348/log220603.log.txt.gz)

**Comment by drawkula** [comment]
A static image spit out via Eric's BASIC via the standard monochrome VGA routine works.

![20220627-032749__VGA-Plugin](https://user-images.githubusercontent.com/9768622/175855037-5a8c5504-164c-4d73-a6c8-4e37c32ac250.png)

A TV-Plugin 4-coulour example is either slooooower than I remember or just gives me a black screen because of something else.  :-/

Additionally sometimes the side bar gets screwed.  At least when loading a new binary or plugin while the previous one still runs.

![20220627-033837__sidebar_glitch](https://user-images.githubusercontent.com/9768622/175855759-e2211821-ad55-4488-b186-fb77121e64d8.png)

SerialIO (only out tested) looked working...

![20220627-034749__SerialIO_and_trying_to_load_new_binary](https://user-images.githubusercontent.com/9768622/175856440-6caf2d38-e79f-4c84-9be6-8b76efa0aa5a.png)

...but trying to load a different example screwed up everything, GEAR got totally unresponsive and I only could `kill` the process.

**Comment by drawkula** [comment]
The VGA- and TV-examples are from: http://yeti.freeshell.org/orgy/flexprop/flexprop.html

http://yeti.freeshell.org/orgy/flexprop/flexprop.html#:flexbasic:example:static-image-vga-512x384x1
This used a modified plugin to correct the aspect ratio.

http://yeti.freeshell.org/orgy/flexprop/flexprop.html#:flexbasic:example:mandelbrot-s4p12-vga-320x240x2
I haven't tested yet just if waiting longer with the new GEAR would have produced an output.

http://yeti.freeshell.org/orgy/flexprop/flexprop.html#:flexbasic:example:cnt-dira-outa
This is my default Logic Probe test.

Lots of other examples not using TV or VGA as output do some serial output but for not testing FlexProp binaries only, the serial-out test was done using the ASCII Mandelbrot examples from: http://yeti.freeshell.org/brain/openspin.html

I 1st started the slower http://yeti.freeshell.org/brain/openspin.html#:example:mandelbrot-s8p24 and wanted to switch to the faster (lower precision) http://yeti.freeshell.org/brain/openspin.html#:example:mandelbrot-s4p12 example and that failed reload is the deadlock snapshot from the SerialIO example.

**Comment by drawkula** [comment]
I was overtired and/or undercaffeinated!

The screen staying black was because I mixed up colour-VGA and TV and ran that example with the TV plugin instead of the one for VGA and even overlooked the "vga" in the example's name: mandelbrot-s4p12-**vga**-320x240x2.bas.binary

Nice!  That already kills one suspected problem.
